<?php
$CONFIG = array (
  'instanceid' => '[INSTANCE_ID]',
  'passwordsalt' => '[PASSWORD_SALT]',
  'secret' => '[SECRET]',
  'trusted_domains' =>
  array (
    0 => 'nextcloud.local',
    1 => '[LAN_IP]',
    2 => '[EXTERNAL_URL]',
  ),
  'datadirectory' => '/mnt/NEXTCLOUD_DATA/',
  'dbtype' => 'mysql',
  'version' => '[VERSION]',
  'overwrite.cli.url' => 'https://nextcloud.local',
  'overwriteprotocol' => 'https',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '[MYSQL_USER]',
  'dbpassword' => '[MYSQL_PASSWORD]',
  'installed' => true,
  'maintenance' => false,
  'maintenance_window_start' => 3,
  'log_type' => 'file',
  'logfile' => '/mnt/NEXTCLOUD_LOGS/nextcloud.log',
  'logfilemode' => 0600,
  'loglevel' => 2,
  'logdateformat' => "Y-m-d H:i:s",
  'logtimezone' => '[TIMEZONE]',
  'log_query' => false,
  'log_rotate_size' => 10 * 1024 * 1024,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'cache_path' => '/mnt/NEXTCLOUD_CACHE',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'password' => '[REDIS_PASSWORD]',
  ),
  'skeletondirectory' => '',
  'htaccess.RewriteBase' => '/',
  'updater.release.channel' => 'stable',
  'enable_previews' => true,
  'preview_max_scale_factor' => 10,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\Movie',
    2 => 'OC\\Preview\\HEIC',
    3 => 'OC\\Preview\\TIFF',
    4 => 'OC\\Preview\\AVI',
    5 => 'OC\\Preview\\BMP',
    6 => 'OC\\Preview\\DNG',
    7 => 'OC\\Preview\\GIF',
    8 => 'OC\\Preview\\JPEG',
    9 => 'OC\\Preview\\MP3',
    10 => 'OC\\Preview\\MP4',
    11 => 'OC\\Preview\\MOV',
    12 => 'OC\\Preview\\MKV',
    13 => 'OC\\Preview\\PNG',
    14 => 'OC\\Preview\\RAW',
    15 => 'OC\\Preview\\XBitMap',
  ),
  'preview_max_x' => 1024,
  'preview_max_y' => 1024,
  'profile.enabled' => false,
  'updatedirectory' => '/var/www/nextcloud_update',
);
